### ISSUE TITLE
Could be great if we have a enum or fields that contains all attributes keys

### ISSUE THREAD

**Issue by mcruzdev** [yupiik/tools-maven-plugin#18]
**Is your feature request related to a problem? Please describe.**

Actually to use `AsciidoctorLikeHtmlRenderer`:

```java
AsciidoctorLikeHtmlRenderer renderer = new AsciidoctorLikeHtmlRenderer(new AsciidoctorLikeHtmlRenderer.Configuration()
                .setAttributes(Map.of("noheader", "true")));
```

We need to know the API internally to know what attribute could be used.

**Describe the solution you'd like**

Add all attribute keys available for `Configuration#attributes` to be used ( enum or field ) and add documentation about it.

Something like it:

```java
 public enum Attributes {
            NO_HEADER_ATTRIBUTE("noheader"),
            DATA_URI_ATTRIBUTE("data-uri"),
            IMAGES_DIR_ATTRIBUTE("imagesdir");

            private final String attributeName;

            Attributes(String attributeName) {
                this.attributeName = attributeName;
            }

            public String key() {
                return attributeName;
            }
        }
```

**Comment by rmannibucau** [comment]
Hi,

Here are some points to keep in mind IMHO - also trying to explain why the original choice was to not go that way at all:

* Attributes depend on the document and renderer so it does not make much sense to have a generic `Attributes` class IMHO but can be an `AsciidoctorLikeHtmlRenderer.Attributes` for example (similarly for Parser and maybe a `CommonAttributes` for shared ones,
* It must likely not define not "hardcoded" attributes (imagesdir for example is a choice in downstream consumers so it shouldn't be pushed up in the producer/renderer),
* There are some cases for prefixed (theorically suffixed but I didn't meet a case yet) attributes where an enum does not work well,
* Whatever is done it is sane to not use the enum anywhere in the API except to get the string key (`key()` is fine or just reuse `toString()`),
* Agree it can make sense to use this enum/constant pattern with a `@Documentation`/`@Description` and generate the doc from there (using an include in the doc as in some other places),
* What must NOT be done without additional configuration is to validate the attributes names, there are tons of cases it is filled and consumed by other part of the rendering process (just meaning enum is a java hack but is semantically not a closed set).

Side note: a final static class with static final constants only can makes as much sense since the enum ordinal will not be an information so maybe something to think about.

Hope it makes sense.

**Comment by mcruzdev** [comment]
Thank you for the quick response and clarification!

**Comment by mcruzdev** [comment]
I have a doubt, I am working on this [pull request](https://github.com/quarkiverse/quarkus-qute-web/pull/102) to make a PoC with this tooling (thank you for this great job)!

**Comment by rmannibucau** [comment]
@mcruzdev looks normal since noheader implies notitle which skips the `=` element (https://github.com/yupiik/tools-maven-plugin/blob/master/asciidoc-java/src/main/java/io/yupiik/asciidoc/renderer/html/AsciidoctorLikeHtmlRenderer.java#L299)

**Comment by mcruzdev** [comment]
Is there a way to have just `<h1>...<h1>` and not the complete HTML? `<!DOCTYPE ...`

**Comment by rmannibucau** [comment]
@mcruzdev guess overriding the `public void visitHeader(final Header header) {` method of the renderer is the fastest adding at the top the line `builder.append(" <h1>").append(escape(header.title())).append("</h1>\n");` before delegating to the `super` impl.

**Comment by fpapon** [comment]
@mcruzdev thank you for using the project! 
Is it possible for you to provide a PR for that?

**Comment by mcruzdev** [comment]
Of course!

Do you mean for the `AsciidoctorLikeHtmlRenderer.Attributes` comment? or `<h1>`?

**Comment by fpapon** [comment]
> Of course!
> 
> Do you mean for the `AsciidoctorLikeHtmlRenderer.Attributes` comment? or `<h1>`?

I mean for the `<h1>`

**Comment by mcruzdev** [comment]
> > Of course!
> 
> > 
> 
> > Do you mean for the `AsciidoctorLikeHtmlRenderer.Attributes` comment? or `<h1>`?
> 
> 
> 
> I mean for the `<h1>`

Tomorrow I will work on it!

**Comment by mcruzdev** [comment]
Thank you @rmannibucau and @fpapon for the helping! I created a new issue to solve the comment above! TY guys!
