### ISSUE TITLE
Diagram macro/bloc support for asciidoc

### ISSUE THREAD

**Issue by jtama** [yupiik/tools-maven-plugin#23]
Is there a plan to support diagram as text for asciidoc

If this is to much work, the actual rendering could be delegated to a remote service such as kroki.

**Comment by rmannibucau** [comment]
@jtama Hi, there is ascii2svg support already (https://www.yupiik.io/tools-maven-plugin/ascii2svg.html - think the dependency just needs to be added).
Personally I'm not a fan of using an external service like kroki cause it makes the build unstable by design and using external tool like mermaid (which is pure js) defeats the goal to be full java.
So it means an integration with plantuml sounds very easy cause it is java.
That said, the parser and renderer (visitor) can be extended to support it, I know that in an app I used the workaround `[source,mermaid]` to have runtime rendering of mermaid. An alternative which works fine is to preparse the files and remplace the blocks (detecting blocks is quite trivial) by prerendered images - tip there: do it using the parser reader to stay ~streaming oriented;).
So my 2cts would be to make block parsing more pluggable (today the supported blocks are hardcoded IIRC) and let the rendering be done by external extensions (maybe plantuml exception which can be done by reflection or with a module like ascii2svg).

hope it makes sense

**Comment by jtama** [comment]
Yes your comment makes sens and of course there is plantuml and mermaid, but there are a lot more formats, hence the third party tool.
But I get your point, thanks.

**Comment by rmannibucau** [comment]
FYI it should already be possible using a decorator or custom visitor (can even extend default one - i use it to make it bootstrap friendly for ex), you will get a `Listing(content, options=[{""="mermaid"}])` for example so you can replace it in your custom visitor by the needed mermaid.js code ensuring you inject mermaid.js in your template. (using mermaid as an example but works globally)

**Comment by jtama** [comment]
Ok delegation does work pretty easily, so let's close the issue !

**Comment by fpapon** [comment]
Thanks for your feedback!
